### ISSUE TITLE
Add transform argument for Web3RpcRequest

### ISSUE THREAD

**Issue by y9san9** [icerockdev/moko-web3#34]
```kotlin
Web3RpcRequest(
    method = "eth_sendRawTransaction",
    params = listOf(signedTransaction),
    paramsSerializer = String.serializer(),
    resultSerializer = String.serializer(),
    transform = ::TransactionHash
)
```
@Alex009, what do you think about such a thing?

It's useful for cases when we want to wrap request result in typed stuff like on screenshot below:
![image](https://user-images.githubusercontent.com/46930374/130612591-4a5be22a-361b-45c2-8d4c-688b9cca7540.png)

Now that works fine and I can add a request to the separate entity, but when I try to use it with a batch request, it becomes kinda verbose because I have a `String` output, but not a `TokenCryptoCurrency?` one.

**Comment by Alex009** [comment]
@y9san9 yes, good idea

**Comment by y9san9** [comment]
For example, the network cannot be extracted from the string and I will make custom serializer like `TokenCryptoCurrencySerializer(network)`
